### ISSUE TITLE
igs dependency

### ISSUE THREAD

**Issue by CarolineOhrman** [jasonsahl/wgfast#2]
Tries to import igs.utils but igs module is removed

On line 29 in wgfast.py `from igs.utils import logging as log_isg`
On line 22 in util.py `import igs_logging as log_isg`

**Comment by jasonsahl** [comment]
Caroline,
Yes, this is a piece of legacy code. I've reworked the whole thing, but will need to do some additional testing and update the manual before I push the changes. In the meantime, you could comment these lines out and it should still work.

**Comment by jasonsahl** [comment]
In the updated code, the reference on line 29 has been removed
For util.py, a file has been added to the repository that should fix this error.

Sorry about that.

Jason
