### ISSUE TITLE
improvement suggested: Naming of readfiles

### ISSUE THREAD

**Issue by CarolineOhrman** [jasonsahl/wgfast#4]
Hi! 
When my read samples were named sample_R1.fastq.gz sample_R2.fastq.gz I got th following error 

Could not determine forward/reverse read status for input file /mnt/rita-data/projects/ringtest/2019/UNSGM/EQAE-3/results/illumina/wgfast/fastq/EN_R1.fastq.gz

When looking through the code I saw that I need a specific format so it worked when changing to sample_R1_00.fastq.gz sample_R2_00.fastq.gz. 

Maybe this could be changed?

**Comment by jasonsahl** [comment]
Please update the repository and see if it fixed your issue
